buildscript {
    ext.kotlinVersion = '2.0.0'
    ext.daggerVersion = '2.57.1'
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
//        maven {
//            url 'https://jitpack.io'
//        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.1'
        //classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:2.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:$kotlinVersion"
        classpath 'com.github.ben-manes:gradle-versions-plugin:0.38.0'
        // Firebase stuff
        // Check that you have the Google Services Gradle plugin v4.3.2 or later
        // (if not, add it).
        classpath 'com.google.gms:google-services:4.4.3'
        // Add the Crashlytics Gradle plugin.
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
        //
        //classpath("com.github.triplet.gradle:play-publisher:3.4.0-agp7.0")
        classpath 'com.github.bjoernq:unmockplugin:0.9.0'
        // Hilt: https://developer.android.com/training/dependency-injection/hilt-android#groovy
        classpath "com.google.dagger:hilt-android-gradle-plugin:$daggerVersion"
        classpath 'com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:2.0.0-1.0.21'
    }
}



allprojects {
    configurations.all {
        resolutionStrategy {
            force "org.jetbrains.kotlin:kotlin-stdlib:${rootProject.ext.kotlinVersion}"
            force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${rootProject.ext.kotlinVersion}"
            force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${rootProject.ext.kotlinVersion}"
            force "org.jetbrains.kotlin:kotlin-stdlib-common:${rootProject.ext.kotlinVersion}"
            force "org.jetbrains.kotlin:kotlin-reflect:${rootProject.ext.kotlinVersion}"
        }
    }

    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        kotlinOptions {
            freeCompilerArgs += [
                "-Xskip-metadata-version-check"
            ]
        }
    }
}
